# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bio-band"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["arrigonialberto86"]
  s.date = "2013-07-25"
  s.description = "Data mining and machine learning algorithms for JRuby "
  s.email = "arrigonialberto86@gmail.com"
  s.executables = ["bio-band"]
  s.extensions = ["ext/mkrf_conf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Jarfile",
    "Jarfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/bio-band",
    "bio-band.gemspec",
    "ext/mkrf_conf.rb",
    "features/create_dataset.feature",
    "features/step_definitions/create_dataset.rb",
    "features/step_definitions/weka_classifiers.rb",
    "features/step_definitions/weka_clustering.rb",
    "features/step_definitions/weka_filters.rb",
    "features/step_definitions/weka_parsers.rb",
    "features/support/env.rb",
    "features/weka_classifiers.feature",
    "features/weka_clustering.feature",
    "features/weka_filters.feature",
    "features/weka_parsers.feature",
    "features/weka_pipeline.feature",
    "lib/bio-band.rb",
    "lib/bio-band/apache.rb",
    "lib/bio-band/apache/stat/inference.rb",
    "lib/bio-band/core.rb",
    "lib/bio-band/core/parser/parser.rb",
    "lib/bio-band/core/type/apache_matrices.rb",
    "lib/bio-band/core/type/attribute.rb",
    "lib/bio-band/core/type/instance.rb",
    "lib/bio-band/core/type/instances.rb",
    "lib/bio-band/core/type/utils.rb",
    "lib/bio-band/weka.rb",
    "lib/bio-band/weka/classifiers/bayes/bayes.rb",
    "lib/bio-band/weka/classifiers/bayes/bayes_utils.rb",
    "lib/bio-band/weka/classifiers/evaluation.rb",
    "lib/bio-band/weka/classifiers/functions/functions.rb",
    "lib/bio-band/weka/classifiers/functions/functions_utils.rb",
    "lib/bio-band/weka/classifiers/lazy/lazy.rb",
    "lib/bio-band/weka/classifiers/lazy/lazy_utils.rb",
    "lib/bio-band/weka/classifiers/trees/trees.rb",
    "lib/bio-band/weka/classifiers/trees/trees_utils.rb",
    "lib/bio-band/weka/clusterers/clusterers.rb",
    "lib/bio-band/weka/clusterers/clusterers_utils.rb",
    "lib/bio-band/weka/db/DatabaseUtils_mysql",
    "lib/bio-band/weka/db/DatabaseUtils_postgresql",
    "lib/bio-band/weka/db/db.rb",
    "lib/bio-band/weka/filters/supervised/attribute/attribute.rb",
    "lib/bio-band/weka/filters/supervised/instance/instance.rb",
    "lib/bio-band/weka/filters/supervised/supervised_utils.rb",
    "lib/bio-band/weka/filters/unsupervised/attribute/attribute.rb",
    "lib/bio-band/weka/filters/unsupervised/instance/instance.rb",
    "lib/bio-band/weka/filters/unsupervised/unsupervised_utils.rb",
    "resources/weather.csv",
    "resources/weather.numeric.arff",
    "spec/bio-band_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/arrigonialberto86/bioruby-band"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Data mining algorithms for JRuby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<jbundler>, [">= 0"])
      s.add_development_dependency(%q<ruport>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<bio>, [">= 1.4.2"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<jbundler>, [">= 0"])
      s.add_dependency(%q<ruport>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<bio>, [">= 1.4.2"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.3.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<jbundler>, [">= 0"])
    s.add_dependency(%q<ruport>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<bio>, [">= 1.4.2"])
  end
end

